version: '3.8'

services:

  db:
    image: postgres:15
    container_name: azship-db
    environment:
      POSTGRES_DB: shipping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: azship-app
    ports:
      - "8080:8080"
    depends_on:
      - db
